[project]
name = "CIPHER-hearing"
version = "0.1.0"
description = "Add a short description here"
authors = ["valorun <ronan@collier-famille.fr>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "==3.11"
numpy = ">=1.26.4,<1.27"
av = "==10.0.0"

[pypi-dependencies]
sounddevice = "==0.4.1"
SoundFile = "==0.10.3.post1"
paho-mqtt = "==2.0.0"
vosk = "==0.3.45"
webrtcvad = "==2.0.10"
faster-whisper = "*"
