---
type: intent
name: regard
slots:
  - name: direction
    entity: direction
utterances:
  - Regardes [direction](à droite)
  - Peux-tu regarder [direction](à gauche) ?

---
type: intent
name: deplacement
slots:
  - name: direction
    entity: direction
utterances:
  - Vas [direction](à droite)
  - Déplaces toi [direction](vers l'avant)
  - Peux-tu aller à [direction](à gauche) ?
  - Diriges toi [direction](en arrière) ?

---
type: intent
name: humeur
utterances:
  - Comment vas-tu ?
  - Ca va bien ?
  - Es-tu en forme ?
  - Tu va bien ?

---
type: intent
name: nom
utterances:
  - Comment t'appelles-tu ?
  - Quel est ton nom ?
  - Dis-moi ton nom
  - C'est quoi ton prénom ?

---
type: intent
name: nom
utterances:
  - Comment t'appelles-tu ?
  - Quel est ton nom ?
  - Dis-moi ton nom
  - C'est quoi ton prénom ?


---
type: intent
name: meteo
slots:
  - name: location
    entity: snips/city
  - name: date
    entity: snips/datetime
utterances:
  - Quel temps fait-il à [location](Paris) ?
  - Dis-moi quel temps il fait à [location](Nantes) [date](aujourd'hui)
  - Il fera quel temps [date](demain) à [location](Marseille) ?
  - C'est quoi la météo pour [date](cette après midi) ?

---
type: intent
name: date
utterances:
  - Quel jour sommes nous ?
  - On est quel jour ?

---
type: entity
name: direction
automatically_extensible: no
values:
- [gauche, à gauche, vers la gauche]
- [droite, à droite, vers la droite]
- [tout droit, en face, devant, en avant, vers l'avant]
- [derrière, en arrière, vers l'arrière]